#cloud-config

package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      keyid: 0EBFCD88

packages:
  - docker-ce

power_state:
  delay: "Now"
  mode: reboot
  message: Reboot after installing Docker
  condition: True

runcmd:
  - sudo curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
